services:
  wordpress:
    build: 
      context:  ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress-files:/var/www/html
    expose:
      - "9000"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - db
      - proxy
    restart: always

  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - wordpress-db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p${DB_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wordpress-files:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - proxy
      - db
    restart: always

volumes:
  wordpress-db:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mysql
      o: bind
  wordpress-files:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind

networks:
  db:
    driver: bridge
  proxy:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "fd00:dead:beef::/64"


