services:
  wordpress:
    build: 
      context:  ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress-files:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - db
      - proxy
    restart: unless-stopped

  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress-db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db
    restart: unless-stopped

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress-files:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - proxy
      - db
    restart: unless-stopped

volumes:
  wordpress-db:
    driver: local
    driver_opts:
      type: none
      device: /home/mpierrot/data/mysql
      o: bind
  wordpress-files:
    driver: local
    driver_opts:
      type: none
      device: /home/mpierrot/data/mysql
      o: bind

networks:
  db:
    driver: bridge
  proxy:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "fd00:dead:beef::/64"


